### ISSUE TITLE
Make iconset configurable?

### ISSUE THREAD

**Issue by lukasoppermann** [dukestreetstudio/zondicons-blade-bridge#1]
Hey @adamwathan,

I really like the idea, but I am using a custom icon set. I was wondering what you think about making the iconset configurable?

My idea for this would be the following:
1. adding another method like `zondicons` but just `icons('media/name-of-icons-set.svg')` which will obviously inline the argument. (Using the default public path as a starting point, so that you can drop and `asset()` path in there (thinking of cache busting here))
2. I guess the path to the folder with the individual icons should be configurable in the config file.

This would be pretty awesome, because it would make this solution more flexible. And the defaults could be set so that it all stays the way it is.

**Comment by adamwathan** [comment]
Hey @lukasoppermann, I'm working on splitting it up a bit here: https://github.com/adamwathan/blade-svg

You should be able to use that library with any icon set, and I'm working on a branch for this repo that will just use that as a dependency:
https://github.com/dukestreetstudio/zondicons-blade-bridge/tree/split

**Comment by lukasoppermann** [comment]
Perfect as always! 😄
